using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace VentCalc.Migrations
{
    public partial class InitData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM [dbo].[NormativeDocumentRoomTypeLinks]                                                                                                                                                                                                                                                                                                                                                    ");
            migrationBuilder.Sql("DELETE FROM [dbo].[NormativeDocuments]                                                                                                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("DELETE FROM [dbo].[NormativeDocumentTypes]                                                                                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("DELETE FROM [dbo].[RoomTypeValues]                                                                                                                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("DELETE FROM [dbo].[RoomTypes]                                                                                                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("DELETE FROM [dbo].[BuildingTypes]                                                                                                                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("DELETE FROM [dbo].[BuildingPurposes]                                                                                                                                                                                                                                                                                                                                                                   ");
            migrationBuilder.Sql("DELETE FROM [dbo].[BuildingKinds]                                                                                                                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("DELETE FROM [dbo].[Cities]                                                                                                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("DELETE FROM [dbo].[Regions]                                                                                                                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[Regions] ON                                                                                                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[Regions] ([Id], [RegionName]) VALUES (1, N'Москва')                                                                                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("INSERT [dbo].[Regions] ([Id], [RegionName]) VALUES (2, N'Ленинградская область')                                                                                                                                                                                                                                                                                                                       ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[Regions] OFF                                                                                                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[Cities] ON                                                                                                                                                                                                                                                                                                                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[Cities] ([Id], [CityName], [RegionId], [TempOutSummer], [TempOutWinter]) VALUES (1, N'Москва', 1, 22.6, -28)                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[Cities] ([Id], [CityName], [RegionId], [TempOutSummer], [TempOutWinter]) VALUES (2, N'Санкт-Петербург', 2, 20.5, -30)                                                                                                                                                                                                                                                                    ");
            migrationBuilder.Sql("INSERT [dbo].[Cities] ([Id], [CityName], [RegionId], [TempOutSummer], [TempOutWinter]) VALUES (3, N'Выборг', 2, 21.2, -29)                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[Cities] ([Id], [CityName], [RegionId], [TempOutSummer], [TempOutWinter]) VALUES (4, N'Кировск', 2, 19.8, -30)                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[Cities] OFF                                                                                                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingKinds] ON                                                                                                                                                                                                                                                                                                                                                           ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingKinds] ([Id], [BuildingKindName]) VALUES (1, N'Гражданские здания')                                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingKinds] ([Id], [BuildingKindName]) VALUES (2, N'Промышленные здания')                                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingKinds] ([Id], [BuildingKindName]) VALUES (3, N'Сельскохозяйственные здания')                                                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingKinds] OFF                                                                                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingPurposes] ON                                                                                                                                                                                                                                                                                                                                                        ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (1, 1, N'Жилые')                                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (2, 1, N'Общественные')                                                                                                                                                                                                                                                                                         ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (3, 2, N'Производственные')                                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (4, 2, N'Энергитическое хозяйство')                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (5, 2, N'Транспортно-складского хозяйства')                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (6, 2, N'Подсобные и вспомогательные')                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (7, 3, N'Животноводческие')                                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (8, 3, N'Птицеводческие')                                                                                                                                                                                                                                                                                       ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingPurposes] ([Id], [BuildingKindId], [BuildingPurposeName]) VALUES (9, 3, N'Культивационные')                                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingPurposes] OFF                                                                                                                                                                                                                                                                                                                                                       ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingTypes] ON                                                                                                                                                                                                                                                                                                                                                           ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (1, 1, N'Жилые дома')                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (2, 1, N'Общежития')                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (3, 1, N'Гостиницы')                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (4, 1, N'Дома отдыха')                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (5, 1, N'Интернаты')                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (6, 1, N'Дома для престарелых')                                                                                                                                                                                                                                                                                    ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (7, 2, N'Учебные заведения (Школы, инстутиты)')                                                                                                                                                                                                                                                                    ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (8, 2, N'Административные (Бизнес центы, офисы)')                                                                                                                                                                                                                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (9, 2, N'Здравохранения и отдыха')                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (10, 2, N'Спортивные (Физкультурно оздоровительные комплексы \"ФОК\", Стадионы и т.п)')                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (11, 2, N'Зрелищные (театры, кинотеатры и т.п)')                                                                                                                                                                                                                                                                   ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (12, 2, N'Торговли, общественного питания и бытового обслуживания (Торговые центры, магазины, столовые и т.п)')                                                                                                                                                                                                    ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (13, 2, N'Траспортные (Аэропорты, ЖД)')                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (14, 2, N'Коммунального хозяйства (Ремонт одежды и т.п)')                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (15, 2, N'Многофункциональныя здания и комплексы')                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (16, 3, N'Производственные здания')                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (17, 3, N'Сборочные цеха заводов')                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (18, 3, N'Фабрики')                                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (19, 4, N'Здания ТЭЦ')                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (20, 4, N'Котельные')                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (21, 4, N'Компрессорные')                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (22, 5, N'Склады')                                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (23, 5, N'Гаражи')                                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (24, 5, N'Депо')                                                                                                                                                                                                                                                                                                   ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (25, 6, N'Административные, бытовые и т.п')                                                                                                                                                                                                                                                                        ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (26, 7, N'Разведения животных: свиней, коров, лошадей и т.п.')                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (27, 8, N'разведения птиц')                                                                                                                                                                                                                                                                                        ");
            migrationBuilder.Sql("INSERT [dbo].[BuildingTypes] ([Id], [BuildingPurposeId], [BuildingTypeName]) VALUES (28, 9, N'Выращивания овощей, цветов и т.п.')                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[BuildingTypes] OFF                                                                                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[RoomTypes] ON                                                                                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (5, N'Бельевая', 1)                                                                                                                                                                                                                                                                                                           ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (6, N'Ванная', 1)                                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (7, N'Гардеробная', 1)                                                                                                                                                                                                                                                                                                        ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (8, N'Гостиная', 1)                                                                                                                                                                                                                                                                                                           ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (9, N'Детская комната ', 1)                                                                                                                                                                                                                                                                                                   ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (10, N'Душвая', 1)                                                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (11, N'Кладовая', 1)                                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (12, N'Кухня с электроплитой', 1)                                                                                                                                                                                                                                                                                             ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (13, N'Машинное отделение лифта', 1)                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (14, N'Мусоросборная камера', 1)                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (15, N'Общая комната', 1)                                                                                                                                                                                                                                                                                                     ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (16, N'Помещение с газоиспользующим оборудованием', 1)                                                                                                                                                                                                                                                                        ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (17, N'Помещение с теплогенераторами с закрытой камерой сгорания общей теплопроизводительностью до 50 кВт ', 1)                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (18, N'Помещение с теплогенераторами с открытой камерой сгорания общей теплопроизводительностью до 50 кВт ', 1)                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (19, N'Совмещённый санузел', 1)                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (20, N'Спальня', 1)                                                                                                                                                                                                                                                                                                           ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypes] ([Id], [RoomTypeName], [BuildingTypeId]) VALUES (21, N'Туалет', 1)                                                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[RoomTypes] OFF                                                                                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[RoomTypeValues] ON                                                                                                                                                                                                                                                                                                                                                          ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (2, NULL, NULL, NULL, 0.2, NULL, 40, NULL, 60, NULL, NULL, 0.2, NULL, 5, 20)                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (3, NULL, 25, NULL, NULL, NULL, 40, NULL, 60, NULL, NULL, NULL, NULL, 6, 20)                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (4, NULL, NULL, NULL, 0.2, NULL, 40, NULL, 60, NULL, NULL, 0.2, NULL, 7, 20)                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (5, N'при общей площади квартиры на одного человека менее 20 м²', NULL, 3, NULL, NULL, 40, NULL, 60, NULL, 3, NULL, NULL, 8, 20)              ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (6, N'при общей площади квартиры на одного чело:века более 20 м²', NULL, NULL, NULL, 30, 40, NULL, 60, NULL, NULL, NULL, 30, 8, 20)           ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (7, N'при общей площади квартиры на одного человека менее 20 м²', NULL, 3, NULL, NULL, 40, NULL, 60, NULL, 3, NULL, NULL, 9, 20)              ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (8, N'при общей площади квартиры на одного чело:века более 20 м²', NULL, NULL, NULL, 30, 40, NULL, 60, NULL, NULL, NULL, 30, 9, 20)           ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (9, NULL, 25, NULL, NULL, NULL, 40, NULL, 60, NULL, NULL, NULL, NULL, 10, 20)                                                                 ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (10, NULL, NULL, NULL, 0.2, NULL, 40, NULL, 60, NULL, NULL, 0.2, NULL, 11, 20)                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (11, NULL, 60, NULL, NULL, NULL, 40, NULL, 60, 60, NULL, NULL, NULL, 12, 20)                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (12, N'По расчету', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13, NULL)                                               ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (13, NULL, NULL, NULL, 1, NULL, 40, NULL, 60, NULL, NULL, 1, NULL, 14, 20)                                                                    ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (14, N'при общей площади квартиры на одного человека менее 20 м²', NULL, 3, NULL, NULL, 40, NULL, 60, NULL, 3, NULL, NULL, 15, 20)            ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (15, N'при общей площади квартиры на одного чело:века более 20 м²', NULL, NULL, NULL, 30, 40, NULL, 60, NULL, NULL, NULL, 30, 15, 20)         ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (16, NULL, 100, NULL, NULL, NULL, 40, NULL, 60, 100, NULL, NULL, NULL, 16, 20)                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (17, N'При установке газовой шшты воздухообмен следует увеличить на 100 м³/ч', NULL, NULL, 1, NULL, 40, NULL, 60, NULL, NULL, 1, NULL, 17, 20)");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (18, N'При установке газовой шшты воздухообмен следует увеличить на 100 м³/ч', NULL, NULL, 1, NULL, 40, NULL, 60, NULL, NULL, 1, NULL, 18, 20)");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (19, NULL, NULL, NULL, NULL, NULL, 40, NULL, 60, NULL, NULL, NULL, NULL, 19, 20)                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (20, N'при общей площади квартиры на одного человека менее 20 м²', NULL, 3, NULL, NULL, 40, NULL, 60, NULL, 3, NULL, NULL, 20, 20)            ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (21, N'при общей площади квартиры на одного чело:века более 20 м²', NULL, NULL, NULL, 30, 40, NULL, 60, NULL, NULL, NULL, 30, 20, 20)         ");
            migrationBuilder.Sql("INSERT [dbo].[RoomTypeValues] ([Id], [Comment], [Exhaust], [ExhaustArea], [ExhaustMultiply], [ExhaustPeople], [HumidityFrom], [HumidityRelative], [HumidityTo], [Inflow], [InflowArea], [InflowMultiply], [InflowPeople], [RoomTypeId], [TempIn]) VALUES (22, NULL, 25, NULL, NULL, NULL, 40, NULL, 60, NULL, NULL, NULL, NULL, 21, 20)                                                                ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[RoomTypeValues] OFF                                                                                                                                                                                                                                                                                                                                                         ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[NormativeDocumentTypes] ON                                                                                                                                                                                                                                                                                                                                                  ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (33, N'СП')                                                                                                                                                                                                                                                                                                                                ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (34, N'СанПиН')                                                                                                                                                                                                                                                                                                                            ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (35, N'МГСН')                                                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (36, N'РМД')                                                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (37, N'ВСН')                                                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (38, N'ВНТП')                                                                                                                                                                                                                                                                                                                              ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (39, N'ВНП')                                                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocumentTypes] ([Id], [Name]) VALUES (40, N'ДБН')                                                                                                                                                                                                                                                                                                                               ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[NormativeDocumentTypes] OFF                                                                                                                                                                                                                                                                                                                                                 ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[NormativeDocuments] ON                                                                                                                                                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("INSERT [dbo].[NormativeDocuments] ([Id], [NormativeDocumentName], [NormativeDocumentTypeId]) VALUES (12, N'СП 54.13330.2016 \"СНиП 31-01-2003 Здания жилые многоквартирные\" ', 33)                                                                                                                                                                                                                      ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [dbo].[NormativeDocuments] OFF                                                                                                                                                                                                                                                                                                                                                     ");                                                                                                                                                                                                                                                                                                                                                                                                                               
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
